default:

    path_country      : "data-public/metadata/oecd/country.csv"
    path_input_oecd   : !expr strftime(Sys.Date(), "data-unshared/derived/oedc-%Y-%m-%d.csv")
    path_input_covid  : !expr strftime(Sys.Date(), "data-unshared/derived/covid-%Y-%m-%d.csv")
    path_oecd_health_chapter: "data-unshared/raw/oecd/health/"

    oced_genders      : !expr c("MEN", "WOMEN")
    oced_ages         : !expr c("1519", "2024", "2554", "5564", "6599")
